// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// single_effect_regression_cpp
List single_effect_regression_cpp(NumericVector y, NumericMatrix X, double V, double residual_variance, Nullable<NumericVector> prior_weights, String optimize_V, double check_null_threshold);
RcppExport SEXP _susieR_single_effect_regression_cpp(SEXP ySEXP, SEXP XSEXP, SEXP VSEXP, SEXP residual_varianceSEXP, SEXP prior_weightsSEXP, SEXP optimize_VSEXP, SEXP check_null_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type residual_variance(residual_varianceSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type prior_weights(prior_weightsSEXP);
    Rcpp::traits::input_parameter< String >::type optimize_V(optimize_VSEXP);
    Rcpp::traits::input_parameter< double >::type check_null_threshold(check_null_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(single_effect_regression_cpp(y, X, V, residual_variance, prior_weights, optimize_V, check_null_threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_susieR_single_effect_regression_cpp", (DL_FUNC) &_susieR_single_effect_regression_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_susieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
