# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

single_effect_regression_cpp <- function(y, X, V, residual_variance = 1, prior_weights = NULL, optimize_V = "none", check_null_threshold = 0) {
    .Call('_susieR_single_effect_regression_cpp', PACKAGE = 'susieR', y, X, V, residual_variance, prior_weights, optimize_V, check_null_threshold)
}

compute_Xty_cpp <- function(X, y) {
    .Call('_susieR_compute_Xty_cpp', PACKAGE = 'susieR', X, y)
}

